ALTER TABLE PET DROP FOREIGN KEY FK_Member_TO_Pet;
ALTER TABLE PET DROP FOREIGN KEY FK_Breed_TO_Pet;
ALTER TABLE symptom DROP FOREIGN KEY FK_Pet_TO_Symptom;
ALTER TABLE pet drop column breed_id;
DROP TABLE breed;
ALTER TABLE pet ADD COLUMN breed VARCHAR(50) NOT NULL AFTER pet_name;

ALTER TABLE Pet
  ADD CONSTRAINT FK_Member_TO_Pet
    FOREIGN KEY (user_id)
    REFERENCES Member (user_id)
    ON DELETE CASCADE;

ALTER TABLE Symptom
  ADD CONSTRAINT FK_Pet_TO_Symptom
    FOREIGN KEY (pet_id)
    REFERENCES Pet (pet_id)
    ON DELETE CASCADE;